### ISSUE TITLE
vsmeta放到视频文件夹无反应

### ISSUE THREAD

**Issue by MaFeelfun** [lunafoxer/JavDB#1]
![QQ截图20240205102809](https://github.com/lunafoxer/JavDB/assets/144716673/196ddcae-8a4a-4566-84e7-fe1946f84f29)
![QQ截图20240205102933](https://github.com/lunafoxer/JavDB/assets/144716673/6a2c9b26-e01d-4299-9ea1-3eb11bdba446)
大佬!vsmeta放到视频文件夹无反应,是什么原因呢?

**Comment by lunafoxer** [comment]
要点“再次搜索所有视频信息”

**Comment by MaFeelfun** [comment]
解决了!感谢大佬.要把文件夹设置成电影,我之前设置的电视节目,所以不行.感谢大佬!
