### ISSUE TITLE
共享刮削数据

### ISSUE THREAD

**Issue by 1525745393** [lunafoxer/JavDB#2]
通过Emby/Jellyfin/TinyMediaManager等刮削到的nfo元数据，转换成群晖Video Station专用vsmeta元数据。

**Comment by 1525745393** [comment]
大佬能添加个功能吗

**Comment by lunafoxer** [comment]
这个项目目前只是用来刮削jav内容，目前不会考虑加入nfo转换vsmeta的功能，你的需求我后期可能会新开一个项目来实现。

**Comment by 1525745393** [comment]
感谢大佬

**Comment by lunafoxer** [comment]
哈喽，你的需求已在最新版本中实现，这个issue我需要关闭它
