### ISSUE TITLE
抓取失败

### ISSUE THREAD

**Issue by smart0114** [lunafoxer/JavDB#5]
<img width="768" alt="20241019153950" src="https://github.com/user-attachments/assets/fe5b843c-fc24-4d9e-91af-12839b85a54f">

这个错误是哪里的原因呢？没有使用说明不太懂

**Comment by 531014023** [comment]
目标网站地址变了，需要修改JavDB.Film.json中的地址为368.com

**Comment by lunafoxer** [comment]
你可以根据实际情况修改JavDB.Film.json文件中src节点对应的网址，目前的有效地址是https://xxxxx368.com

**Comment by smart0114** [comment]
挺好用的，就是元数据只能手动逐个导出吗？要是可以批量就方便了

**Comment by smart0114** [comment]
> 你可以根据实际情况修改JavDB.Film.json文件中src节点对应的网址，目前的有效地址是https://xxxxx368.com

挺好用的，就是元数据只能手动逐个导出吗？要是可以批量就方便了

**Comment by lunafoxer** [comment]
hello，试试我的新项目javdb.docker吧
